default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  username: postgres
  password: mysecretpassword
  reconnect: true

development:
  <<: *default
  database: wichteler-development
