<% require "rails"; require "dotenv-rails"; Dotenv::Rails.load %>

# Name of your application. Used to uniquely configure containers.
service: wichteler

# Name of the container image.
image: bonflintstone/wichteler

# Deploy to these servers.
servers:
  web:
    - 49.13.203.148

proxy:
  ssl: true
  host: wichteler.bonflintstone.com

registry:
  username: bonflintstone
  password: <%= ENV["KAMAL_REGISTRY_PASSWORD"] %>

env:
  secret:
    - RAILS_MASTER_KEY

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

volumes:
  - "wichteler:/rails/storage"

asset_path: /rails/public/assets

builder:
  arch: amd64
